<x-layout-design>
    <div>
        <p>
            <a href="#">Category Name</a>
        </p>
        <h1 class="post-title">The Blog Post Title Here</h1>
        <p>
            &mdash; 25th December 2014, 8:34pm
        </p>
        <div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur porta tristique turpis, a dignissim velit lobortis a. Proin nec varius dui. In ut diam ac enim vestibulum feugiat. Integer at velit sem. Vestibulum id erat nibh. Cras pharetra elementum magna in hendrerit. Sed interdum nunc eu risus rutrum, quis elementum sem sodales. Morbi nec eleifend lorem. Maecenas vel ex orci. Nunc pretium, tortor et dictum pulvinar, felis quam ullamcorper ipsum, in tincidunt lectus ipsum et augue. Donec sollicitudin fringilla nisl at eleifend. Nulla vulputate arcu at ipsum dictum, at congue sem finibus. Nulla volutpat ultricies velit, ac porta sem mollis id. Nulla rhoncus feugiat finibus. Pellentesque volutpat mollis neque, quis iaculis mi luctus eu.</p>
            <p>Vivamus pulvinar urna id pellentesque maximus. Nulla molestie accumsan nibh, blandit facilisis nisi blandit sed. In euismod porta sem, ac gravida eros porttitor in. Integer sit amet sapien non ipsum vehicula maximus. Curabitur et aliquet turpis. Praesent auctor rutrum urna, ac porttitor ante pulvinar sit amet. Curabitur eu sapien magna. Nullam sed rutrum urna. Donec iaculis augue ac interdum lacinia. Nam non massa eu leo porta lobortis. Nunc vitae vulputate arcu. Pellentesque ut lorem lacinia, finibus ipsum et, consequat ligula. Proin ultrices lorem quis neque laoreet tempor at et diam. Nulla at orci tristique, luctus libero volutpat, imperdiet diam. Maecenas et ornare est. Praesent consequat dignissim nibh, ut tincidunt quam varius in.</p>
            <img src="https://picsum.photos/id/237/1500/500" />
            <p>Morbi orci nibh, condimentum quis magna sit amet, pellentesque pretium urna. Morbi dolor eros, sollicitudin ac lacinia nec, molestie quis nibh. Cras nec justo odio. Maecenas sed metus at tortor placerat tristique. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque finibus odio vel turpis condimentum maximus. Praesent diam mauris, tristique sed malesuada fermentum, porttitor a tellus. Cras faucibus nisl aliquam nisl luctus viverra. Donec iaculis mattis lacus, vitae porttitor est. Proin maximus porttitor mi, in molestie mi scelerisque sed. Sed in mauris urna.</p>
            <p>Morbi sem leo, viverra quis lacinia et, viverra vitae diam. Vestibulum varius lacinia tortor in porta. Vivamus accumsan elit elit, at bibendum magna maximus sit amet. Aenean dictum dui quis odio sagittis efficitur. Nunc dignissim ligula eget massa placerat bibendum. Donec eu quam sodales, faucibus felis sit amet, lobortis odio. Curabitur sed gravida justo.</p>
            <img src="https://picsum.photos/id/50/650/400" />
            <img src="https://picsum.photos/id/59/650/400" />
            <p>Sed non ligula magna. Suspendisse tempor eleifend blandit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus pulvinar ut ipsum et suscipit. Aliquam a felis eget diam ullamcorper mattis sit amet pellentesque dui. Mauris risus magna, dignissim sit amet dui vel, tempor tristique tellus. Praesent volutpat nulla vel purus elementum, ac pulvinar nunc consequat. Sed dui nunc, interdum vitae velit eu, posuere imperdiet urna. Suspendisse laoreet purus nec volutpat convallis. Vivamus quis lobortis quam. Suspendisse varius leo arcu, vel scelerisque massa volutpat ac.</p>
            <p>Sed sed lacus pulvinar, volutpat ex nec, rhoncus nibh. Aenean neque tellus, consectetur sed tellus ac, porttitor lobortis quam. Nunc ac varius turpis. Nullam mattis, eros vitae auctor facilisis, orci turpis consequat justo, ut aliquam ex sem nec est. Mauris laoreet fermentum erat, et posuere est commodo in. Suspendisse ultricies, metus et dignissim molestie, metus sapien dictum mauris, quis finibus erat tortor at massa. Proin sit amet est id purus tristique lacinia non a mi. Maecenas sed felis eu enim malesuada ullamcorper at et nulla. Nam aliquet lacus ut urna interdum, sed porta nunc feugiat. Vestibulum in ultricies orci. Maecenas tincidunt ipsum quis diam volutpat vehicula. Duis fermentum lobortis odio, vestibulum imperdiet elit convallis sed. Ut tincidunt urna id interdum aliquet. Mauris vitae auctor arcu. Nunc aliquet tincidunt lacus non ultrices.</p>
            <p>Vestibulum in mattis dolor. Cras neque magna, aliquam id libero at, interdum euismod turpis. Integer sagittis eros sed leo venenatis, et consectetur libero faucibus. Aenean non dignissim massa. Etiam porta facilisis felis. Proin sit amet nunc id turpis ultrices lacinia ut eu dolor. Quisque ligula leo, interdum vel maximus vel, accumsan id nibh. Fusce pellentesque justo vitae tortor suscipit ultricies. Donec finibus sed tellus eu accumsan. Vestibulum ut tristique quam. Ut varius dignissim elit, faucibus lacinia mauris placerat nec.</p>
            <p>Nulla facilisi. Duis sed rutrum eros. Proin et finibus arcu. Duis non pharetra velit. Nullam at tincidunt diam, sit amet pretium risus. Aliquam erat volutpat. Etiam fermentum, turpis quis maximus pretium, nunc odio suscipit augue, vehicula ultrices ante lectus vitae elit. Proin nisi massa, faucibus vitae libero a, accumsan pretium diam. Maecenas at dignissim tortor. Nullam ac sodales augue. </div></p>
    </div>
</x-layout-design>

